apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: {{ .Values.pipelineNamespace }}
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFqZEhJQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJBVDNjRzRBKwpDQnpWQTV2VHBuZjV4a0FBQUFFQUFBQUFFQUFBQXpBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJREdKR25YdUEvK3FKSGg0CmdEbkEvQXAwdFljbUtDRnBmSDMzcHYwUmRRWWtBQUFBb0RBVDVRUDhDK0lNSnpBMmxWenZ5a1J6NFNNUGdVOUpVNHBuQ2oKVXdxS3h0SDJlVWtWV2F6cnhyNW10a2hzUFpVcnl0S21uVzVESmhzMGJpNmQ0bGlZMnZLaTU1bGtKQ0ZJNVlITThHR0grNAp1SmkyNTErdEJXRnpNaUUvMnc1YVBMZ2FPcHFLS25wU3NmbHZIRTBpVUxmcWpWc3FRYUx5L2J5QTY0QVgreHpYVFZ0djMrCnR2U0swVW50K2VNTlJ4TzlhcGlBcVo3UUxJNTNVQXdhRk15ckE9Ci0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  # This is non-standard, but its use is encouraged to make this more secure.
  # If it is not provided then the git server's public key will be requested
  # when the repo is first fetched.
  # known_hosts: <known-hosts>