apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: {{ .Values.pipelineNamespace }}
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: raphac-mar
  password: Juc@P@t0 