apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ .Values.pipelineName }}
  namespace: {{ .Values.pipelineNamespace }}
spec:
  params:
  - name: git-repo-url
    description: The git repository url
  - name: git-revision
    description: The git commit SHA
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  - name: git-branch
    description: branch
  - name: git-commit
    description: commit
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(tt.params.git-repo-name)-$(tt.params.git-branch)-webhook-
    spec:
      taskRunTemplate:
        serviceAccountName: pipeline
      pipelineRef:
        name: {{ .Values.pipelineName }}
      params:
      - name: appName
        value: $(tt.params.git-repo-name)
      - name: appNamespace
        value: $(tt.params.git-repo-name)-$(tt.params.git-branch)
      - name: imageRegistryNamespace
        value: {{ .Values.imageRegistryNamespace }}
      #
      - name: repoUrl
        value: $(tt.params.git-repo-url)
      - name: branchName
        value: $(tt.params.git-branch)
      - name: gitCommit
        value: $(tt.params.git-revision)
      workspaces:
      - name: shared-workspace
        persistentVolumeClaim:
          claimName: shared-workspace-pvc
